#!/usr/bin/env python3
"""Generate wiki/PROJECT_MAP.md from the repository tree."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "wiki" / "PROJECT_MAP.md"

IGNORE_DIRS = {
    ".git",
    "__pycache__",
    "node_modules",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "env",
}

SUMMARY = {
    ".agents/": "Harness-neutral role contracts.",
    ".claude/": "Claude Code command and skill adapters.",
    ".codex/": "Codex usage notes.",
    ".opencode/": "OpenCode usage notes.",
    "wiki/": "Compact agent-facing project memory.",
    "knowledge/": "Structured registries and handoff files.",
    "sources/": "Raw or long user/agent source material.",
    "results/": "Generated experiment outputs.",
    "templates/": "Reusable document and registry templates.",
    "scripts/wiki/": "Helper scripts for agents and curators.",
}


def should_skip(path: Path) -> bool:
    return any(part in IGNORE_DIRS for part in path.parts)


def tree_lines(root: Path, max_depth: int) -> list[str]:
    lines: list[str] = []

    def walk(path: Path, prefix: str, depth: int) -> None:
        if depth > max_depth:
            return
        entries = sorted(
            [p for p in path.iterdir() if not should_skip(p.relative_to(root))],
            key=lambda p: (not p.is_dir(), p.name.lower()),
        )
        for index, entry in enumerate(entries):
            connector = "`-- " if index == len(entries) - 1 else "|-- "
            rel = entry.relative_to(root).as_posix()
            display = entry.name + ("/" if entry.is_dir() else "")
            lines.append(f"{prefix}{connector}{display}")
            if entry.is_dir() and depth < max_depth:
                extension = "    " if index == len(entries) - 1 else "|   "
                walk(entry, prefix + extension, depth + 1)

    lines.append(root.name + "/")
    walk(root, "", 1)
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-depth", type=int, default=3)
    args = parser.parse_args()

    summary_rows = "\n".join(
        f"| `{path}` | {purpose} |" for path, purpose in sorted(SUMMARY.items())
    )
    tree = "\n".join(tree_lines(ROOT, args.max_depth))
    content = f"""# Project Map

Generated by `scripts/wiki/build_tree.py`.

## Directory Summary

| Path | Purpose |
|---|---|
{summary_rows}

## Tree

```text
{tree}
```

## Curator Notes

Add short explanations for project-specific code directories here after the
implementation grows.
"""
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()

