#!/usr/bin/env python3
"""Generate agent-wiki/wiki/PROJECT_MAP.md from a host project tree."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


WIKI_ROOT = Path(__file__).resolve().parents[2]
OUT = WIKI_ROOT / "wiki" / "PROJECT_MAP.md"

IGNORE_DIRS = {
    ".git",
    "__pycache__",
    "node_modules",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "env",
}

COLLAPSE_DIRS = {
    "results",
    "figures",
    "wandb",
    "checkpoints",
}

SUMMARY = {
    "agent-wiki/": "Curator-owned compact project memory subsystem.",
    "agent-wiki/wiki/": "Compact agent-facing project memory.",
    "agent-wiki/knowledge/": "Structured registries and handoff files.",
    "agent-wiki/sources/": "Raw or long user/agent source material.",
    "src/": "Host project source code, if present.",
    "experiments/": "Host experiment entrypoints, configs, or scripts, if present.",
    "results/": "Host generated experiment outputs, usually linked from run cards.",
    "figures/": "Host generated figures or paper artifacts.",
    "paper-wiki/": "Host paper-writing workspace, if present.",
}


def resolve_project_root(value: str | None) -> Path:
    if value:
        return Path(value).resolve()
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            cwd=WIKI_ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode == 0 and result.stdout.strip():
            return Path(result.stdout.strip()).resolve()
    except OSError:
        pass
    return WIKI_ROOT


def should_skip(path: Path) -> bool:
    return any(part in IGNORE_DIRS for part in path.parts)


def should_collapse(path: Path) -> bool:
    parts = set(path.parts)
    return bool(parts & COLLAPSE_DIRS)


def tree_lines(root: Path, max_depth: int) -> list[str]:
    lines: list[str] = []

    def walk(path: Path, prefix: str, depth: int) -> None:
        if depth > max_depth:
            return
        entries = sorted(
            [p for p in path.iterdir() if not should_skip(p.relative_to(root))],
            key=lambda p: (not p.is_dir(), p.name.lower()),
        )
        for index, entry in enumerate(entries):
            rel = entry.relative_to(root)
            connector = "`-- " if index == len(entries) - 1 else "|-- "
            display = entry.name + ("/" if entry.is_dir() else "")
            if entry.is_dir() and should_collapse(rel):
                display += " ..."
            lines.append(f"{prefix}{connector}{display}")
            if entry.is_dir() and depth < max_depth and not should_collapse(rel):
                extension = "    " if index == len(entries) - 1 else "|   "
                walk(entry, prefix + extension, depth + 1)

    lines.append(root.name + "/")
    walk(root, "", 1)
    return lines


def existing_summary_rows(project_root: Path) -> str:
    rows = []
    for path, purpose in sorted(SUMMARY.items()):
        if (project_root / path).exists() or path.startswith("agent-wiki/"):
            rows.append(f"| `{path}` | {purpose} |")
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", default="", help="Host project root. Use '.' from host root.")
    parser.add_argument("--max-depth", type=int, default=3)
    args = parser.parse_args()

    project_root = resolve_project_root(args.project_root or None)
    summary_rows = existing_summary_rows(project_root)
    tree = "\n".join(tree_lines(project_root, args.max_depth))
    content = f"""# Project Map

Generated by `agent-wiki/scripts/wiki/build_tree.py`.

Host project root: `{project_root}`
Agent-wiki root: `{WIKI_ROOT}`

## Directory Summary

| Path | Purpose |
|---|---|
{summary_rows}

## Tree

```text
{tree}
```

## Curator Notes

Add short explanations for project-specific code directories here after the
implementation grows. Keep this map compact; link to source files or topic hubs
instead of pasting code.
"""
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(WIKI_ROOT)}")


if __name__ == "__main__":
    main()
